global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'docker-host-alpha'

rule_files:
  - "alert.rules"
  - "host-and-hardware.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

